# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Wonyoung Park
title: Senior Network System Administrator
email: holly31521@gmail.com
website: www.github.com/Wonyoungpark

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Wonyoungpark
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>
  

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: WA3I-Automated-Scoring
        # link_text: Project Website
        github: TeamLab/WAI-Automated-Scoring
        link: http://zubiri.gachon.ac.kr:8000/
        additional_links:
          - title:  인공지능과 서술형 
            icon: fab fa-youtube
            url: https://www.youtube.com/embed/20h195JbXSQ
          - title:  notion/WA3I-Automated-Scoring
            icon: fab fa-link
            url: https://www.notion.so/Ruby-Autograding-7163b70b739d4ef8b994c48f7964b6b2
        quote: >
          창의성 개발을 위한 서술형 지원 AI 프로그램 개발
        description: | # this will include new lines to allow paragraphs
          - 프로젝트 기간 : 2020.03 ~ 현재 <br>
          - 지원 기관 : <a href="https://lms.kofac.re.kr/front/main/index.do" target="_blank"> 한국과학창의재단 </a><br>
          - 사용자 기능 정의 및 화면 설계서 작성<br>
          - 프로젝트 DB 설계 및 개발<br>
            -MySQL, SQLite, PostgreSQL<br>
          - 웹 페이지 개발<br>
            - Django : web back-end 개발<br>
            - Bootstrap, HTML, css, jQuery, Ajax : web front-end 개발<br>
            - Python : request 데이터 처리, 채점 모델 API 연결<br>
            - Docker : 시스템 구축 및 실행<br>
            
      - layout: top-middle
        title: Ruby-Autograding
        # link_text: Project Website
        github: Wonyoungpark/Ruby-Autograding
        additional_links:
          - title:  notion/Ruby-Autograding
            icon: fab fa-link
            url: https://www.notion.so/Ruby-Autograding-7163b70b739d4ef8b994c48f7964b6b2
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          AI 자동 채점 지원 프로그램 개발
        description: | # this will include new lines to allow paragraphs
          - 프로젝트 기간 : 2020.08 ~ 현재 <br>
          - 지원 기관 : <a href="http://theteamlab.io/" target="_blank">TEAMLAB</a><br>
          - 사용자 기능 정의 및 화면 설계서 작성<br>
          - 프로젝트 DB 설계 및 개발<br>
            - MySQL, SQLite<br>
          - 웹 페이지 개발<br>
            - Vue.js, Node.js, Express : web back-end 개발<br>
          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
